/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namegenerator;

import java.awt.CheckboxGroup;
import java.awt.Desktop;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Falcuun
 */
public class Randomizer extends javax.swing.JFrame {

    /**
     * Creates new form Randomizer
     */
    public Randomizer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();

        buttonGroup1.add(jCheckBox1);
        buttonGroup1.add(jCheckBox2);
        buttonGroup1.add(jCheckBox3);
        buttonGroup1.add(jCheckBox4);
        buttonGroup1.add(jCheckBox5);
        buttonGroup1.add(jCheckBox6);
        buttonGroup1.add(jCheckBox7);
        buttonGroup1.add(jCheckBox8);
        buttonGroup1.add(jCheckBox9);
        buttonGroup1.add(jCheckBox10);
        buttonGroup1.add(jCheckBox11);
        buttonGroup1.add(jCheckBox12);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Champion Generator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButton1.setForeground(new java.awt.Color(0, 255, 51));
        jButton1.setText("Generate a Random Champion");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(0);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generate!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jCheckBox1.setText("1350");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("3150");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("6300");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("450");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("4800");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setSelected(true);
        jCheckBox6.setText("all");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Sort by price");

        jButton2.setText("Show Guide");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aatrox", "Ahri", "Akali", "Alistar", "Amumu", "Anivia", "Annie", "Ashe", "Aurelion Sol", "Azir", "Bard", "Blitzcrank", "Brand", "Braum", "Caitlyn", "Cassiopeia", "Cho'Gath", "Corki", "Darius", "Diana", "Dr.Mundp ", "Draven", "Ekko ", "Elise", "Evenlynn", "Ezreal", "Fiddlesticks", "Fiora", "Fizz", "Galio", "GangPlank", "Garen", "Gnar", "Gragas", "Graves", "Hecarim", "Heimerdinger", "Illaoi", "Irelia", "Ivern", "Janna", "Jarvan IV", "Jax", "Jayce", "Jhin", "Jinx", "Kalista", "Karma", "Karthus", "Kassadin", "Katarina", "Kayle", "Kennen", "Kha'Zix", "Kindred", "Kled", "Kog'Maw", "LeBlanc", "Lee Sin", "Leona", "Lissandra", "Lucian", "Lulu", "Lux", "Malphite", "Malzahar", "Maokai", "Master Yi", "Miss Fortune", "Monkey King", "Mordekaiser", "Morgana", "Nami ", "Nasus", "Nautilus", "Nidalee", "Nocturne", "Nunu", "Olaf", "Orianna", "Pantheon", "Poppy", "Quinn", "Rammus", "Rek'Sai", "Renekton", "Rengar", "Riven", "Rumble", "Ryze", "Sejuani", "Shaco", "Shen", "Shyvana", "Singed", "Sion", "Sivir", "Skarner", "Sona", "Soraka", "Swain", "Syndra", "Tahm Kench", "Taliyah", "Talon", "Taric", "Teemo", "Thresh", "Tristana", "Trundle", "Tryndamere", "Twisted Fate", "Twitch", "Udyr", "Urgot", "Varus", "Vayne", "Veigar", "Vel'Koz", "Vi", "Viktor", "Vladimir", "Volibear", "Warwick", "Xerath", "Xin Zhao", "Yasuo", "Yorick", "Zac", "Zed", "Ziggs", "Zilean", "Zyra", "Camille", "Select Champion...." }));
        jComboBox1.setSelectedIndex(134);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Choose champion from the list:");

        jLabel5.setText("Sort by role");

        jCheckBox7.setText("Assassassins");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("Fighters");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Mages");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("Marksman");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox11.setText("Supports");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox12.setText("Tanks");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jLabel5)
                                    .addComponent(jCheckBox9)
                                    .addComponent(jCheckBox10)
                                    .addComponent(jCheckBox11))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(345, 345, 345)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(12, 12, 12))
                                            .addComponent(jCheckBox6)
                                            .addComponent(jCheckBox2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox1)
                                            .addComponent(jCheckBox4)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox4)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(46, 46, 46))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox12)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Champions ch;
    ChampionsTwo ch2;
    Roles rl;
    RolesComboBox rlcb;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Makes an object of the Champion class (Class with all the Champion names)
        ch = new Champions(jLabel1, jLabel3);

        rl = new Roles(jLabel3);
        // Calls a method setChampions()(names) and setIcon() from "Champions" class for unfiltered generating
        if (jCheckBox6.isSelected()) {
            ch.setNoFilterChampion();
            ch.setNoFilterIcon();
            jComboBox1.setSelectedIndex(ch.getRandom1());
        }
        //If jCheckBox4 is thicked 
        // Calls a method setIcon() and setChampions()(Names) from "Champions" class for 450 Champions
        if (jCheckBox4.isSelected()) {
            ch.setFourFiftyChampions();
            ch.setFourFityIcons();
            jComboBox1.setSelectedIndex(ch.getRandom2());
        }
        //If jCheckBox1 is thicked 
        // Calls a method setIcon() and setChampions()(Names) from class Champions for 1350 champions
        if (jCheckBox1.isSelected()) {
            ch.setThirteenFiftyChampions();
            ch.setThirteenFiftyIcons();
            jComboBox1.setSelectedIndex(ch.getRandom3());
        }
        //If jCheckBox2 is thicked 
        // Calls a method setIcon() and setChampions()(Names) from class Champions for 1350 champions
        if (jCheckBox2.isSelected()) {
            ch.setThirtyOneFiftyChampions();
            ch.setThirtyOneFiftyIcons();
            jComboBox1.setSelectedIndex(ch.getRandom4());
        }
        //If jCheckBox5 is thicked 
        // Calls a method setIcon() and setChampions()(Names) from class Champions for 1350 champions
        if (jCheckBox5.isSelected()) {
            ch.setFourtyEightHundredChampions();
            ch.setFourtyEightHundredIcons();
            jComboBox1.setSelectedIndex(ch.getRandom5());
        }
        //If jCheckBox3 is thicked 
        //Calls a method setIcon() and setChampions()(Names) from class Champions for 1350 champions
        if (jCheckBox3.isSelected()) {
            ch.setSixtyThreeHundredChampions();
            ch.setSixtyThreeHundredIcons();
            jComboBox1.setSelectedIndex(ch.getRandom6());
        }
        if (jCheckBox7.isSelected()) {
            jLabel1.setText(rl.getAssassins());
            rl.setAssassinsIcons();
            jComboBox1.setSelectedIndex(rl.rA());
        }
        if (jCheckBox8.isSelected()) {
            jLabel1.setText(rl.getFighters());
            rl.setFightersIcons();
            jComboBox1.setSelectedIndex(rl.rF());
        }
        if (jCheckBox9.isSelected()) {
            jLabel1.setText(rl.getMages());
            rl.setMagesIcons();
            jComboBox1.setSelectedIndex(rl.rM());
        }
        if (jCheckBox10.isSelected()) {
            jLabel1.setText(rl.getMarksman());
            rl.setMarksmanIcons();
            jComboBox1.setSelectedIndex(rl.rMa());
        }
        if (jCheckBox11.isSelected()) {
            jLabel1.setText(rl.getSupports());
            rl.setSupportsIcons();
            jComboBox1.setSelectedIndex(rl.rS());
        }
        if (jCheckBox12.isSelected()) {
            jLabel1.setText(rl.getTanks());
            rl.setTanksIcons();
            jComboBox1.setSelectedIndex(rl.rT());
        }


    }//GEN-LAST:event_jButton1ActionPerformed
    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Amumu", "Annie", "Ashe", "Garen", "Kayle", "Master Yi", "Nunu", "Poppy", "Ryze", "Singed", "Sivir", "Soraka", "Warwick", "Generate"}));
        jComboBox1.setSelectedIndex(13);
    }//GEN-LAST:event_jCheckBox4ActionPerformed
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Alistar", "cho Gath", "Dr. Mundo", "Evelynn", "Fiddlesticks", "Janna", "Jax", "Malphite", "Morgana", "Nasus", "Rammus", "Sion", "Taric",
            "Teemo", "Tristana", "Tryndamere", "Twisted Fate", "Udyr", "Veigar", "Xin Zhao", "Zilean", "Generate"}));

        jComboBox1.setSelectedIndex(21);
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Akali", "Anivia", "Blitzcrank", "Corki", "Galio", "Gangplank", "Gragas", "Heimerdinger", "Karma", "Karthus", "Kassadin", "Katarina",
            "LeBlanc", "Lux", "Miss Fortune", "Mordekaiser", "Nidalee", "Olaf", "Pantheon", "Shaco", "Shen", "Shyvana", "Sona", "Twitch", "Urgot", "Generate"}));
        jComboBox1.setSelectedIndex(25);
    }//GEN-LAST:event_jCheckBox2ActionPerformed
    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Ahri", "Brand", "Caitlyn", "Cassiopiea", "Darius", "Diana", "Draven", "Ezreal", "Fiora", "Fizz", "Graves", "Hecarim", "Ireali", "Jarvan IV",
            "Jayce", "Kennen", "Kog Maw", "Lee Sin", "Leona", "Lulu", "Malzahar", "Maokai", "Nautilus", "Nocturne", "Orianna", "Renekton", "Riven", "Rumble", "Sejuani", "Skarner", "Swain", "Talon",
            "Trundle", "Varus", "Vayne", "Viktor", "Vladimir", "Volibear", "Wukong", "Xerath", "Yorick", "Ziggs", "Zyra", "Generate"}));
        jComboBox1.setSelectedIndex(43);
    }//GEN-LAST:event_jCheckBox5ActionPerformed
    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Aatrox", "Aurelion Sol", "Azir", "Bard", "Braum", "Camille", "Ekko", "Elise", "Gnar", "Illaoi", "Ivern", "Jhin", "Jinx", "Kalista", "Kha Zix", "Kindred",
            "Kled", "Lissandra", "Lucian", "Nami", "Quinn", "Rek Sai", "Rengar", "Syndra", "Tahm Kench", "Taliyah", "Thresh", "Vel Koz", "Vi", "Yasuo", "Zac", "Zed", "Generate"}));
        jComboBox1.setSelectedIndex(32);
    }//GEN-LAST:event_jCheckBox3ActionPerformed
    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Aatrox", "Ahri", "Akali", "Alistar", "Amumu", "Anivia", "Annie", "Ashe", "Aurelion Sol", "Azir",
            "Bard", "Blitzcrank", "Brand", "Braum", "Caitlyn", "Cassiopeia", "Cho'Gath", "Corki", "Darius", "Diana",
            "Dr.Mundo", "Draven", "Ekko", "Elise", "Evenlynn", "Ezreal", "Fiddlesticks", "Fiora", "Fizz", "Galio", "GangPlank", "Garen",
            "Gnar", "Gragas", "Graves", "Hecarim", "Heimerdinger", "Illaoi", "Irelia", "Ivren", "Janna", "Jarvan IV",
            "Jax", "Jayce", "Jhin", "Jinx", "Kalista", "Karma", "Karthus", "Kassadin", "Katarina", "Kayle", "Kennen", "Kha'Zix", "Kindred",
            "Kled", "Kog'Maw", "LeBlanc", "Lee Sin", "Leona", "Lissandra", " Lucian", "Lulu", "Lux", "Malphite", "Malzahar", "Maokai",
            "Master Yi", "Miss Fortune", "Wukong", "Mordekaiser", "Morgana", "Nami", "Nasus", "Nautilus", "Nidalee", "Nocturne", "Nunu", "Olaf",
            "Orianna", "Pantheon", "Poppy", "Quinn", "Rammus", "Rek'Sai", "Renekton", "Rengar", "Riven", "Rumble", "Ryze", "Sejuani",
            "Shaco", "Shen", "Shyvana", "Singed", "Sion", "Sivir", "Skarner", "Sona", "Soraka", "Swain", "Syndra",
            "Tahm Kench", "Taliyah", "Talon", "Taric", "Teemo", "Thresh", "Tristana", "Trundle", "Tryndamere", "Twisted Fate", "Twitch", "Udyr",
            "Urgot", "Varus", "Vayne", "Veigar", "Vel'Koz", "Vi", "Viktor", "Vladimir", "Volibear", "Warwick", "Xerath", "Xin Zhao", "Yasuo",
            "Yorick", "Zac", "Zed", "Ziggs", "Zilean", "Zyra", "Camille", "Select Champion...."}));
        jComboBox1.setSelectedIndex(134);
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (jCheckBox6.isSelected()) {
            try {
                ch.openWebGuideNoFilter();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jCheckBox4.isSelected()) {
            try {
                ch.openWebGuide450();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (jCheckBox1.isSelected()) {
            try {
                ch.openWebGuide1350();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (jCheckBox2.isSelected()) {
            try {
                ch.openWebGuide3150();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (jCheckBox5.isSelected()) {
            try {
                ch.openWebGuide4800();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (jCheckBox3.isSelected()) {
            try {
                ch.openWebGuide6300();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jCheckBox7.isSelected()) {
            try {
                rl.openWebGuideAssassins();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jCheckBox8.isSelected()) {
            try {
                rl.openWebGuideFighters();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jCheckBox9.isSelected()) {
            try {
                rl.openWebGuideMages();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jCheckBox10.isSelected()) {
            try {
                rl.openWebGuideMarksman();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jCheckBox11.isSelected()) {
            try {
                rl.openWebGuideSupports();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jCheckBox12.isSelected()) {
            try {
                rl.openWebGuideTanks();
            } catch (Exception ex) {
                //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ch2 = new ChampionsTwo(jComboBox1);
        rlcb = new RolesComboBox(jComboBox1);
        //Generating Guides from the Check Box selected Champion!
        try {
            if (jCheckBox6.isSelected()) {
                ch2.setWebGuidesFromComboBox();
            }
            if (jCheckBox4.isSelected()) {
                ch2.openWebGuide450();
            }
            if (jCheckBox1.isSelected()) {
                ch2.openWebGuide1350();
            }
            if (jCheckBox2.isSelected()) {
                ch2.openWebGuide3150();
            }
            if (jCheckBox3.isSelected()) {
                ch2.openWebGuide6300();
            }
            if (jCheckBox5.isSelected()) {
                ch2.openWebGuide4800();
            }
            if (jCheckBox7.isSelected()) {
                rlcb.opnWebguideAssassins();
            }
            if (jCheckBox8.isSelected()) {
                rlcb.openWebGuideFighters();
            }
            if (jCheckBox9.isSelected()) {
                rlcb.openWebGuideMages();
            }
            if (jCheckBox10.isSelected()) {
                rlcb.openWebGuideMarksman();
            }
            if (jCheckBox11.isSelected()) {
                rlcb.openWebGuideSupports();
            }
            if (jCheckBox12.isSelected()) {
                rlcb.openWebGuideTanks();
            }

        } catch (Exception ex) {
            //  Logger.getLogger(Randomizer.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        String names[] = {"Aatrox", "Ahri", "Akali", "Alistar", "Amumu", "Anivia", "Annie", "Ashe", "Aurelion Sol", "Azir",
            "Bard", "Blitzcrank", "Brand", "Braum", "Caitlyn", "Cassiopeia", "Cho'Gath", "Corki", "Darius", "Diana",
            "Dr.Mundo", "Draven", "Ekko", "Elise", "Evenlynn", "Ezreal", "Fiddlesticks", "Fiora", "Fizz", "Galio", "GangPlank", "Garen",
            "Gnar", "Gragas", "Graves", "Hecarim", "Heimerdinger", "Illaoi", "Irelia", "Ivren", "Janna", "Jarvan IV",
            "Jax", "Jayce", "Jhin", "Jinx", "Kalista", "Karma", "Karthus", "Kassadin", "Katarina", "Kayle", "Kennen", "Kha'Zix", "Kindred",
            "Kled", "Kog'Maw", "LeBlanc", "Lee Sin", "Leona", "Lissandra", " Lucian", "Lulu", "Lux", "Malphite", "Malzahar", "Maokai",
            "Master Yi", "Miss Fortune", "Wukong", "Mordekaiser", "Morgana", "Nami", "Nasus", "Nautilus", "Nidalee", "Nocturne", "Nunu", "Olaf",
            "Orianna", "Pantheon", "Poppy", "Quinn", "Rammus", "Rek'Sai", "Renekton", "Rengar", "Riven", "Rumble", "Ryze", "Sejuani",
            "Shaco", "Shen", "Shyvana", "Singed", "Sion", "Sivir", "Skarner", "Sona", "Soraka", "Swain", "Syndra",
            "Tahm Kench", "Taliyah", "Talon", "Taric", "Teemo", "Thresh", "Tristana", "Trundle", "Tryndamere", "Twisted Fate", "Twitch", "Udyr",
            "Urgot", "Varus", "Vayne", "Veigar", "Vel'Koz", "Vi", "Viktor", "Vladimir", "Volibear", "Warwick", "Xerath", "Xin Zhao", "Yasuo",
            "Yorick", "Zac", "Zed", "Ziggs", "Zilean", "Zyra", "Camille", "Select Champion...."};

        String names450[] = {"Amumu", "Annie", "Ashe", "Garen", "Kayle", "Master Yi", "Nunu", "Poppy", "Ryze", "Singed", "Sivir", "Soraka", "Warwick", "Generate"};
        String names1350[] = {"Alistar", "cho Gath", "Dr. Mundo", "Evelynn", "Fiddlesticks", "Janna", "Jax", "Malphite", "Morgana", "Nasus", "Rammus", "Sion", "Taric",
            "Teemo", "Tristana", "Tryndamere", "Twisted Fate", "Udyr", "Veigar", "Xin Zhao", "Zilean", "Select Champion...."};
        String names3150[] = {"Akali", "Anivia", "Blitzcrank", "Corki", "Galio", "Gangplank", "Gragas", "Heimerdinger", "Karma", "Karthus", "Kassadin", "Katarina",
            "LeBlanc", "Lux", "Miss Fortune", "Mordekaiser", "Nidalee", "Olaf", "Pantheon", "Shaco", "Shen", "Shyvana", "Sona", "Twitch", "Urgot", "Select Champion...."};
        String names4800[] = {"Ahri", "Brand", "Caitlyn", "Cassiopiea", "Darius", "Diana", "Draven", "Ezreal", "Fiora", "Fizz", "Graves", "Hecarim", "Ireali", "Jarvan IV",
            "Jayce", "Kennen", "Kog Maw", "Lee Sin", "Leona", "Lulu", "Malzahar", "Maokai", "Nautilus", "Nocturne", "Orianna", "Renekton", "Riven", "Rumble", "Sejuani", "Skarner", "Swain", "Talon",
            "Trundle", "Varus", "Vayne", "Viktor", "Vladimir", "Volibear", "Wukong", "Xerath", "Yorick", "Ziggs", "Zyra", "Select Champion...."};
        String names6300[] = {"Aatrox", "Aurelion Sol", "Azir", "Bard", "Braum", "Camille", "Ekko", "Elise", "Gnar", "Illaoi", "Ivern", "Jhin", "Jinx", "Kalista", "Kha Zix", "Kindred",
            "Kled", "Lissandra", "Lucian", "Nami", "Quinn", "Rek Sai", "Rengar", "Syndra", "Tahm Kench", "Taliyah", "Thresh", "Vel Koz", "Vi", "Yasuo", "Zac", "Zed", "Select Champion...."};
        String assassins[] = {"Akali", " Ekko", "Evelynn", "Fizz", "Kassadin", "Katarina", " KhaZix", "LeBlanc", "MasterYi", "Nidalee", "Nocturne", "Rengar", "Shaco", "Talon", "Zed", "Select Champion..."};
        String fighters[] = {"Aatrox", "Camille", "Darius", "Diana", "Dr. Mundo", "Fiora", "Gangplank", "Garen", "Gnar", "Gragas", "Hecarim", "Illaoi", "Irelia", "Jax", "Jayce", "Kayle", "Kled", "Lee Sin", "Wukong", "Mordekaiser", "Nasus", "Olaf", "Pantheon", "Rek'Sai", "Renekton", "Riven", "Rumble", "Shyvana", "Skarner", "Trundle", "Tryndamere", "Udyr", "Vi", "Volibear", "Warwick", "Xin Zhao", "Yasuo", "Yorick", "Select Champion..."};
        String tank[] = {"Alistar", "Amumu", "Blitzcrank", "Cho'Gath", "Galio", "JarvanIV", "Leona", "Malphite", "Maokai", "Nautilus", "Poppy", "Rammus", "Sejuani", "Shen", "Singed", "Sion", "Zac", "Select Champion..."};
        String mages[] = {"Ahri", "Anivia", "Annie", "Aurelion Sol", "Azir", "Brand", "Cassiopeia", "Elise", "Fiddlesticks", "Heimerdinger", "Karma", "Karthus", "Kenne", "Lissandra", "Lux", "Malzahar", "Morgana", "Orianna", "Ryze", "Swain", "Syndra", "Taliyah", "Twisted Fate", "Veigar", "Vel'Koz", "Viktor", "Vladimir", "Xerath", "Ziggs", "Zyra", "Select Champion..."};
        String supports[] = {"Bard", "Braum", "Ivern", "Janna", "Lulu", "Nami", "Nunu", "Sona", "Soraka", "Tahm Kench", "Taric", "Thresh", "Zilean", "Select Champion..."};
        String marksman[] = {"Ashe", "Caitlyn", "Corki", "Draven", "Ezreal", "Graves", "Jhin", "Jinx", "Kalista", "Kindred", "Kog'Maw", "Lucian", "Miss Fortune", "Quinn", "Sivir", "Teemo", "Tristana", "Twitch", "Urgot", "Varus", "Vayne", "Select Champion..."};

        for (String name : names) {
            if (jComboBox1.getSelectedIndex() < names.length) {
                ch = null;
                rlcb = null;
                rl = null;
            }
        }

        ch2 = new ChampionsTwo(jComboBox1, jLabel3);
        rlcb = new RolesComboBox(jComboBox1, jLabel3);

        try {
            if (jCheckBox6.isSelected()) {
                jLabel1.setText(names[jComboBox1.getSelectedIndex()]);
                ch2.setIconsFromComboBox();
            }
            if (jCheckBox4.isSelected()) {
                jLabel1.setText(names450[jComboBox1.getSelectedIndex()]);
                ch2.setFourFityIcons();
            }
            if (jCheckBox1.isSelected()) {
                jLabel1.setText(names1350[jComboBox1.getSelectedIndex()]);
                ch2.setThirteenFiftyIcons();
            }
            if (jCheckBox2.isSelected()) {
                jLabel1.setText(names3150[jComboBox1.getSelectedIndex()]);
                ch2.setThirtyOneFiftyIcons();
            }
            if (jCheckBox3.isSelected()) {
                jLabel1.setText(names6300[jComboBox1.getSelectedIndex()]);
                ch2.setSixtyThreeHundredIcons();
            }
            if (jCheckBox5.isSelected()) {
                jLabel1.setText(names4800[jComboBox1.getSelectedIndex()]);
                ch2.setFourtyEightHundredIcons();
            }
            if (jCheckBox6.isSelected()) {
                jLabel1.setText(names[jComboBox1.getSelectedIndex()]);
                ch2.setIconsFromComboBox();
            }
            if (jCheckBox4.isSelected()) {
                jLabel1.setText(names450[jComboBox1.getSelectedIndex()]);
                ch2.setFourFityIcons();
            }
            if (jCheckBox7.isSelected()) {
                jLabel1.setText(assassins[jComboBox1.getSelectedIndex()]);
                rlcb.setAssassinsIcons();
            }
            if (jCheckBox8.isSelected()) {
                jLabel1.setText(fighters[jComboBox1.getSelectedIndex()]);
                rlcb.setFightersIcons();
            }
            if (jCheckBox9.isSelected()) {
                jLabel1.setText(mages[jComboBox1.getSelectedIndex()]);
                rlcb.setMagesIcons();
            }
            if (jCheckBox10.isSelected()) {
                jLabel1.setText(marksman[jComboBox1.getSelectedIndex()]);
                rlcb.setMarksmanIcons();
            }
            if (jCheckBox11.isSelected()) {
                jLabel1.setText(supports[jComboBox1.getSelectedIndex()]);
                rlcb.setSupportsIcons();
            }
            if (jCheckBox12.isSelected()) {
                jLabel1.setText(tank[jComboBox1.getSelectedIndex()]);
                rlcb.setTanksIcons();
            }

            //ch2.setIconsFromComboBox();
        } catch (NullPointerException npe) {

        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Akali", " Ekko", "Evelynn", "Fizz", "Kassadin", "Katarina", " KhaZix", "LeBlanc", "MasterYi", "Nidalee", "Nocturne", "Rengar", "Shaco", "Talon", "Zed", "Select Champion..."}));
        jComboBox1.setSelectedItem("Select Champion...");
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Ahri", "Anivia", "Annie", "Aurelion Sol", "Azir", "Brand", "Cassiopeia", "Elise", "Fiddlesticks", "Heimerdinger", "Karma", "Karthus", "Kenne", "Lissandra", "Lux", "Malzahar", "Morgana", "Orianna", "Ryze", "Swain", "Syndra", "Taliyah", "Twisted Fate", "Veigar", "Vel'Koz", "Viktor", "Vladimir", "Xerath", "Ziggs", "Zyra", "Select Champion..."}));
        jComboBox1.setSelectedItem("Select Champion...");

    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Aatrox", "Camille", "Darius", "Diana", "Dr. Mundo", "Fiora", "Gangplank", "Garen", "Gnar", "Gragas", "Hecarim", "Illaoi", "Irelia", "Jax", "Jayce", "Kayle", "Kled", "Lee Sin", "Wukong", "Mordekaiser", "Nasus", "Olaf", "Pantheon", "Rek'Sai", "Renekton", "Riven", "Rumble", "Shyvana", "Skarner", "Trundle", "Tryndamere", "Udyr", "Vi", "Volibear", "Warwick", "Xin Zhao", "Yasuo", "Yorick", "Select Champion..."}));
        jComboBox1.setSelectedItem("Select Champion...");
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Ashe", "Caitlyn", "Corki", "Draven", "Ezreal", "Graves", "Jhin", "Jinx", "Kalista", "Kindred", "Kog'Maw", "Lucian", "Miss Fortune", "Quinn", "Sivir", "Teemo", "Tristana", "Twitch", "Urgot", "Varus", "Vayne", "Select Champion..."}));
        jComboBox1.setSelectedItem("Select Champion...");
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Bard", "Braum", "Ivern", "Janna", "Lulu", "Nami", "Nunu", "Sona", "Soraka", "Tahm Kench", "Taric", "Thresh", "Zilean", "Select Champion..."}));
        jComboBox1.setSelectedItem("Select Champion...");
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Alistar", "Amumu", "Blitzcrank", "Cho'Gath", "Galio", "JarvanIV", "Leona", "Malphite", "Maokai", "Nautilus", "Poppy", "Rammus", "Sejuani", "Shen", "Singed", "Sion", "Zac", "Select Champion..."}));
        jComboBox1.setSelectedItem("Select Champion...");
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Randomizer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Randomizer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Randomizer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Randomizer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Randomizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
